### ISSUE TITLE
Training log on the ImageNet

### ISSUE THREAD

**Issue by LiheYoung** [kyle-1997/simmatch#6]
Hi,

Thank you for your fantastic work and codebase! I am trying to reproduce the ImageNet results, would you mind providing its training logs? It will help me a lot!

**Comment by kyle-1997** [comment]
Here is the test log for [1%](https://drive.google.com/file/d/16_QgHxMIlgZ7xOnGqpp75LAz7zTuYmEQ/view?usp=sharing) setting and [10%](https://drive.google.com/file/d/1Zpyc9drqNE1Mu6lbJo5GKwoPf0jUjYAU/view?usp=sharing) setting. Please fell free to ask me if you need more information, but I've been quite busy recently, so I may not be able to reply in time.
