### ISSUE TITLE
Question about reported results

### ISSUE THREAD

**Issue by islam-nassar** [kyle-1997/simmatch#7]
Hi there, thanks for your excellent work. 

I just wanted to confirm about the reported results for CIFAR datasets in your paper: taking a look at the log files you shared [here](https://drive.google.com/file/d/1S59Eyt2klV02xW4FS46Mcir4L2jsIjeR/view?usp=sharing), the results in the paper seem to be the best EMA accuracy during training. Is that correct?

**Comment by kyle-1997** [comment]
Yes
